Work in progress

diff --git a/ecmake b/ecmake
--- a/ecmake
+++ b/ecmake
@@ -35,6 +35,7 @@ function usage()
 	
 	echo "ecmake recognizes some specific options in addition to cmake options, see below" >&2
 	echo >&2
+	
     echo "Additional targets:"
     echo "  distclean                    = Clean cmake generated files " 
     echo "  eclipse                      = Generate eclipse project" 
@@ -57,6 +58,7 @@ function usage()
 	[ $opt_ccache -eq 1 ] &&    echo "  --[no-]ccache                = Use [or not] ccache to speed up build (used by default)" >&2
 	[ $opt_ccache -eq 1 ] ||    echo "  --[no-]ccache                = Use [or not] ccache to speed up build" >&2
 	echo "  --verbose                    = Enable verbose build" >&2
+    echo >&2
 	exit 0
 }
 
@@ -391,11 +393,11 @@ fi
 
 if [ $opt_configure -eq 1 ]
 then
-	[ -f /usr/lib/ecmake/configure.cmake ] && config=/usr/lib/ecmake/configure.cmake
-	[ -f /usr/local/lib/ecmake/configure.cmake ] && config=/usr/local/lib/ecmake/configure.cmake
+	[ -f /usr/lib/ecmake/cmake_script.cmake ] && config=/usr/lib/ecmake/cmake_script.cmake
+	[ -f /usr/local/lib/ecmake/cmake_script.cmake ] && config=/usr/local/lib/ecmake/cmake_script.cmake
 	if [ "_${config}" == "_" ]
 	then
-		echo "configure.cmake not found" >&2
+		echo "cmake_script.cmake not found" >&2
 		exit 1 
 	fi
 	cmake_opts="$cmake_opts -DCMAKE_TOOLCHAIN_FILE=${config}"
diff --git a/ecpack b/ecpack
--- a/ecpack
+++ b/ecpack
@@ -2,24 +2,77 @@
 
 xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
 
+opt_mirror="localhost"
+opt_repo=testing
+opt_user=$USER
+
 function usage()
 {
 	cpack --help 
 	echo >&2
+
+	echo "ecpack recognizes some specific options in addition to cpack options, see below" >&2
+	echo >&2
+
     echo "Additional targets:"
     echo "  publish                      = Publish package to debian repository" >&2
 	echo >&2
-	echo "ecpack recognizes some specific options in addition to cpack options, see below" >&2
+
+	echo "Build options:"
+	echo "  --mirror=url                 = Debian mirror repository url (default ${opt_mirror})" >&2
+	echo "  --repo=name                  = Repository to publish package (default ${opt_repo})" >&2
+	echo "  --user=name                  = User allowed to connect with public key on server (default $USER)" >&2
 	echo >&2
-	echo "  --mirror=url                 = Debian mirror repository url" >&2
-	echo "  --repo=name[,name2...]       = Repository to publish package (default testing)" >&2
+
 	exit 0
+}
+
+function check_ssh() {
+	ssh -o PasswordAuthentication=no ${opt_user}@${opt_mirror} exit &>/dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "Error: publickey connection to ${debian_repo_url} failed"
+		return 0
+	fi
+	
+	return 1
+}
+
+function get_release_version() {
+	name=$1
+	version=$2	
+	
+	check_ssh() && exit 1
+	
+	# get rebuild increment from debian repository
+	package_list="$(ssh ${opt_user}@${opt_mirror} reprepro dumpreferences | grep ${name}_${version})"
+	
+	set -e
+	# check if a rebuild version exists
+	rebuild=$(echo $package_list | grep "${name}_${version}-" | sed "s#.*${name}_${version}-\([0-9]*\)_.*#\1#g" | sort | tail -n1)
+	if [[ "_$rebuild" != "_" ]]
+	then
+		# found a previous rebuild version, increment it
+		(( rebuild = rebuild + 1 ))
+	else
+		if [[ "_$(echo $package_list | grep ${package_name}_${package_version}_)" != "_" ]]
+		then
+			# found a release, add first rebuild
+			rebuild=1
+		fi
+	fi
+	
+	return rebuild
+}
+
+function publish() {
+	echo
 }
 
 cpack_opts=""
 
 opt_target=0
-opt_help=1
+opt_help=0
 while [[ "_$*" != "_" ]]
 do
     if [ "_$(echo "$1" | grep '=')" != "_" ]
@@ -33,6 +86,15 @@ do
 
 	if [[ "$filt_arg" == "--help" ]]; then
 	    opt_help=1
+	elif [[ "$filt_arg" == "publish" ]]; then
+	    tgt_publish=1
+	    cpack_opts="${cpack_opts} package"
+	elif [[ "$filt_arg" == "--mirror" ]]; then
+	    opt_mirror=${value_arg}
+	elif [[ "$filt_arg" == "--repo" ]]; then
+	    opt_repo=${value_arg}
+	elif [[ "$filt_arg" == "--user" ]]; then
+	    opt_user=${value_arg}
 	else
 	    args="$args $1"
 	fi
@@ -43,3 +105,5 @@ done
 [ $opt_help -eq 1 ] && usage
 
 eval "cpack $args $cpack_opts"
+
+[ $tgt_publish -eq 1 ] && publish
